config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'reports#index'
  resources :reports do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    member do
      get 'artist'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :text, presence: true

  belongs_to :user
  belongs_to :report
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :report_find, only: [:create, :destroy]

  def create
    @comment = @report.comments.build(comment_params)
    if @comment.save
      render :index
    else
      render :error
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end

  private

  def report_find
    @report = Report.find(params[:report_id])
  end

  def comment_params
    params.require(:comment).permit(:text, :report_id).merge(user_id: current_user.id)
  end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <li class="comment-field">
    <span class="comment-user">
      <%= link_to comment.user.nickname, user_path(comment.user.id) %>
    </span>
    <span class="comment-text">
      <%= comment.text %>
    </span>
    <% if user_signed_in? && comment.user.id == current_user.id %>
      <%= link_to "コメントを削除する", report_comment_path(comment.report_id, comment.id), method: :delete, remote: true, data: {confirm: "コメントを削除しますか？"}, class:"comment-delete-btn" %>
    <% end %>
  </li>
<% end %>

app/views/comments/error.js.erb
$("#comment-error").html("<%= j(render 'shared/error-messages', model: @comment) %>")

app/views/comments/index.js.erb
$("#report-comment-box").html("<%= j(render 'index', { comments: @comment.report.comments}) %>")
$("textarea").val('')