config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'reports#index'
  resources :reports do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    member do
      get 'artist'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :report
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :report_find,  only: [:create, :destroy]

  def create
    @like = Like.new(user_id: current_user.id, report_id: @report.id)
    @like.save
    render :index
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, report_id: @report.id)
    @like.destroy
    render :index
  end

  private

  def report_find
    @report = Report.find(params[:report_id])
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_report.html.erb
<% if user_signed_in? %>
  <% if current_user.liked_by?(report.id) %>
    <%= link_to "イイネ☆を外す", report_like_path(current_user.id, report.id), class: "like-link", method: :delete, remote: true %>
    <i class="fas fa-hand-peace unlike-btn"></i>
    <%= report.likes.count%>
  <% else %>
    <%= link_to "イイネ☆", report_likes_path(current_user.id, report.id), class: "like-link", method: :post, remote: true %> 
    <i class="far fa-hand-peace like-btn"></i>
    <%= report.likes.count%>
  <% end %>
<% else %>
  <div class="no-login-like">イイネ☆</div>
  <%= report.likes.count%>
<% end %>

app/views/likes/index.js.erb
$(".report-likes").html("<%= j(render 'report', { report: @report}) %>")