config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'reports#index'
  resources :reports do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    member do
      get 'artist'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :destroy]
end

app/models/report.rb
class Report < ApplicationRecord
  
  with_options presence: true do
    validates :title
    validates :artist
    validates :text
    validates :violent, presence: { message: "の評価は星0.5以上を選んでください" }
    validates :with_family, presence: { message: "の評価は星0.5以上を選んでください" }
    validates :preparation, presence: { message: "の評価は星0.5以上を選んでください" }
  end

  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  
  scope :search, -> (search_params) do
    return if search_params.blank?

    title_like(search_params[:title])
    .artist_like(search_params[:artist])
    .text_like(search_params[:text])
    .recommend_like(search_params[:recommend])
  end

  scope :title_like, -> (title) { where('title LIKE ?', "%#{title}%") if title.present? }
  scope :artist_like, -> (artist) { where('artist LIKE ?', "%#{artist}%") if artist.present? }
  scope :text_like, -> (text) { where('text LIKE ?', "%#{text}%") if text.present? }
  scope :recommend_like, -> (recommend) { where('recommend LIKE ?', "%#{recommend}%") if recommend.present? }
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :artist]
  before_action :report_find, only: [:show, :edit, :update, :destroy, :artist]
  before_action :back_to_index, only: [:edit, :update, :destroy]

  def index
    @reports = Report.includes(:user).order(created_at: "DESC")
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      redirect_to root_path, notice: "レポートを投稿しました！"
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @report.comments.includes(:user).order(created_at: "DESC")
    @like = Like.new
  end

  def edit
  end

  def update
    if @report.update(report_params)
      redirect_to report_path(@report.id), notice: "レポートを更新しました！"
    else
      render :edit
    end    
  end

  def destroy
    if @report.destroy
     redirect_to root_path, notice: "レポートを削除しました！"
    else
      render :edit
    end
  end

  def artist
    @reports = Report.where(artist: @report.artist)
  end

  def search
    @search_params = report_search_params
    @reports = Report.search(@search_params).joins(:user)
  end

  private

  def report_params
    params.require(:report).permit(:title, :artist, :text, :recommend, :violent, :violent_reason, :with_family, :with_family_reason, :preparation, :preparation_reason).merge(user_id: current_user.id)
  end

  def report_find
    @report = Report.find(params[:id])    
  end

  def report_search_params
    params.fetch(:search, {}).permit(:title, :artist, :text, :recommend)
  end

  def back_to_index
    if current_user.id != @report.user.id
      redirect_to root_path
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/artist.html.erb
<%= render "shared/second-header" %>

<div class="artist-show">
 <div class="artist-show-field">
   <h3 class="ribbon8">アーティスト</h3>
 </div>
 <div class="artist-show-field">
  <span class="artist-show-name">
   <%= @report.artist %>
  </span>
 </div>
 <div class="artist-show-wrap">
  <div class="artist-show-subtitle">
   <h3 class="ribbon8">ライブの評価</h3>
  </div>
  <div class="artist-show-rate-box">
   <span class="artist-show-rate-subtitle">
    ライブの激しさ
   </span>
   <div class="artist-show-rate-contents">
    <%= @reports.average(:violent).to_f.round(1) %>
   </div>
   <div class="artist-show-rate" id="artist-star-violent" ></div>
  </div>
  <div class="artist-show-rate-box">
   <span class="artist-show-rate-subtitle">
    女性・家族連れの方へのオススメ度
   </span>
   <div class="artist-show-rate-contents">
    <%= @reports.average(:with_family).to_f.round(1) %>
   </div>
   <div class="artist-show-rate" id="artist-star-with-family" ></div>
  </div>
  <div class="artist-show-rate-box">
   <span class="artist-show-rate-subtitle">
    ライブの予習必要度
   </span>
   <div class="artist-show-rate-contents">
    <%= @reports.average(:preparation).to_f.round(1) %>
   </div>
   <div class="artist-show-rate" id="artist-star-preparation" ></div>
  </div>

  <%= render "shared/artist-show" %>

 </div>
 <div class="artist-show-field">
  <h3 class="ribbon8">レポート一覧</h3>
 </div>
 <ul class="artist-show-reports-box">
  <% @reports.each do |report| %>
  <li class="artist-show-report">
   <%= link_to report_path(report.id) do %>
   <div class="artist-show-user">
    <%= report.user.nickname %>
   </div>
   <div class="artist-show-title">
    <%= report.title %>
   </div>
   <% end %>
  </li>
  <% end %>
 </ul>
</div>

<%= render "shared/footer" %>

app/views/reports/artist_show.html.erb
<%= render "shared/second-header" %>

<div class="artist-show">
 <div class="artist-show-field">
   <h3 class="ribbon8">アーティスト</h3>
 </div>
 <div class="artist-show-field">
  <span class="artist-show-name">
   <%= @report.artist %>
  </span>
 </div>
 <div class="artist-show-wrap">
  <div class="artist-show-subtitle">
   <h3 class="ribbon8">ライブの評価</h3>
  </div>
  <div class="artist-show-rate-box">
   <span class="artist-show-rate-subtitle">
    ライブの激しさ
   </span>
   <div class="artist-show-rate-contents">
    <%= @reports.average(:violent).to_f.round(1) %>
   </div>
   <div class="artist-show-rate" id="artist-star-violent" ></div>
  </div>
  <div class="artist-show-rate-box">
   <span class="artist-show-rate-subtitle">
    女性・家族連れの方へのオススメ度
   </span>
   <div class="artist-show-rate-contents">
    <%= @reports.average(:with_family).to_f.round(1) %>
   </div>
   <div class="artist-show-rate" id="artist-star-with-family" ></div>
  </div>
  <div class="artist-show-rate-box">
   <span class="artist-show-rate-subtitle">
    ライブの予習必要度
   </span>
   <div class="artist-show-rate-contents">
    <%= @reports.average(:preparation).to_f.round(1) %>
   </div>
   <div class="artist-show-rate" id="artist-star-preparation" ></div>
  </div>

  <%= render "shared/artist-show" %>

 </div>
 <div class="artist-show-field">
  <h3 class="ribbon8">レポート一覧</h3>
 </div>
 <ul class="artist-show-reports-box">
  <% @reports.each do |report| %>
  <li class="artist-show-report">
   <%= link_to report_path(report.id) do %>
   <div class="artist-show-user">
    <%= report.user.nickname %>
   </div>
   <div class="artist-show-title">
    <%= report.title %>
   </div>
   <% end %>
  </li>
  <% end %>
 </ul>
</div>

<%= render "shared/footer" %>

app/views/reports/edit.html.erb
<%= render "shared/second-header" %>

<div class="report-contents" >
  <div class="report-form-main" >
   <h1 class="report-form-subtitle">ライブレポートの記入</h1>
   <%= form_with model: @report, url: report_path, class: "report-form", local: true do |f| %>

   <%= render 'shared/error-messages', model: f.object %>

   <div class="report-form-feild">
    <div class="report-form-wrap">
     <label class="form-text">タイトル</label>
     <span class="indispensable">必須</span>
    </div>
    <div class="report-short-box">
      <%= f.text_field :title, class:"report-title", autofocus:true, placeholder:"レポートのタイトル(40文字まで)", maxlength:"40" %>
    </div>
   </div>
   <div class="report-form-feild">
    <div class="report-form-wrap">
     <label class="form-text">アーティスト</label>
     <span class="indispensable">必須</span>
    </div>
    <div class="report-short-box">
      <%= f.text_field :artist, class:"report-artist", placeholder: "アーティスト名(正式名称で30文字)", maxlength:"30" %>
    </div>
   </div>
   <div class="report-form-field">
    <div class="report-form-wrap">
     <label class="form-text">本文</label>
     <span class="indispensable">必須</span>
    </div>
    <div class="report-form-text-box">  
     <%= f.text_area :text, class:"report-text", placeholder:"レポート内容(1200文字まで)", maxlength:"1200" %>
    </div>
   </div>
   <div class="report-form-field">
    <div class="report-form-wrap">
     <label class="form-text">このライブのオススメポイント</label>
     <span class="indispensable" style="color: black;">任意</span>
    </div>
    <div class="report-form-evaluate-box">
     <%= f.text_area :recommend, class:"report-item", placeholder:"オススメポイント(100文字)", maxlength:"100" %>
    </div>
   </div>
   <div class="report-rate-form">
    <div class="report-form-wrap">
     <label class="form-text">このライブの激しさ</label>
     <span class="indispensable">必須</span>
    </div>
    <div class="rate-form-field">
     <%= f.label :violent, "評価", class: "violent" %>
     <span class="rate-detail" id="edit-violent-<%= @report.id %>"></span>
    </div>
    <div class="report-form-field">
      <div class="report-form-wrap">
      <label class="form-text">理由</label>
      <span class="indispensable" style="color: black;">任意</span>
      </div>
      <div class="report-form-evaluate-box">
        <%= f.text_area :violent_reason, class:"report-item", placeholder:"理由(100文字まで)", maxlength:"100" %>
      </div>
    </div>
   </div>
   <div class="report-rate-form">
    <div class="report-form-wrap">
     <label class="form-text">女性、家族連れの方へのオススメ度</label>
     <span class="indispensable">必須</span>
    </div>
    <div class="rate-form-field">
     <%= f.label :with_family, "評価", class: "with-family" %>
     <span class="rate-detail" id="edit-with_family-<%= @report.id %>"></span>
    </div>
    <div class="report-form-field">
      <div class="report-form-wrap">
      <label class="form-text">理由</label>
      <span class="indispensable" style="color: black;">任意</span>
      </div>
      <div class="report-form-evaluate-box">
        <%= f.text_area :with_family_reason, class:"report-item", placeholder:"理由(100文字まで)", maxlength:"100" %>
      </div>
    </div>
   </div>
   <div class="report-rate-form">
    <div class="report-form-wrap">
     <label class="form-text">ライブの予習必要度</label>
     <span class="indispensable">必須</span>
    </div>
    <div class="rate-form-field">
     <%= f.label :preparation, "評価", class: "preparation" %>
     <span class="rate-detail" id="edit-preparation-<%= @report.id %>"></span>
    </div>
    <div class="report-form-field">
      <div class="report-form-wrap">
      <label class="form-text">理由</label>
      <span class="indispensable" style="color: black;">任意</span>
      </div>
      <div class="report-form-evaluate-box">
        <%= f.text_area :preparation_reason, class:"report-item", placeholder:"理由(100文字まで)", maxlength:"100" %>
      </div>
    </div>
   </div>

   <%= render 'shared/rate-edit' %>

   <div class="report-form-submit">
    <%= f.submit "変更する", class:"report-send-btn" %>
   </div>
   <% end %>
  </div> 
</div>

<%= render "shared/footer" %>

app/views/reports/index.html.erb
<%= render "shared/main-header" %>

<%= render "shared/flash" %>

<div class="top-main">
 <div class="top-image-contents">
  <%= image_tag 'main-top-image', width:"100%", height:"426", class:"top-image" %>
 </div>
 <div class="web-explain-contents">
  <h2 class="explain-title">
   MUSIC BEATS SPIRITのサービス
  </h2>
  <ul class="service-list">
   <li class="lists">
    <%= image_tag "report-image.png", class:"list-pict" %>
    <h3 class="explain-report">
     ライブレポートの投稿！！
    </h3>
    <p class="explain-sentence">
     ひとりひとりの熱いレポートを書くことも読むこともできます。
    </p>
   </li>
   <li class="lists">
   <%= image_tag "shinpai_woman.png", class:"list-pict" %>
    <h3 class="explain-report">
     ライブ前の不安を解消できる！！
    </h3>
    <p class="explain-sentence-2">
     ライブに初めて行く時、「ライブって激しくて怖いのかな」「家族で行ってみたいけど、子供がいると難しいのかな」
     <br>「事前にノリとか確認しないといけないのかな」と様々なことを不安に思うものです。
     <br>このサイトのライブレポートで事前にライブの特徴を知ることができます。
    </p>
   </li>
  </ul>
 </div>
 <div class="report-index">
  <h2 class="index-title">
   レポート一覧
  </h2>
 </div>
 <ul class="report-lists">
  <% if @reports.present? %>
   <% @reports.each do |report| %>
    <li class="list">
     <%= link_to report_path(report.id) do %>
     <div class="reports-user-nickname">
      <h3 class="user-nickname">
       <%= report.user.nickname %>
      </h3>
     </div>
     <div class="reports-title">
      <h3 class="title">
       <%= report.title %>
      </h3>
     </div>
     <% end %>
    </li>
   <% end %>
  <% else %>
   <div class="report-none">
    <h3 class="report-none-message">レポートを投稿して下さい</h3>
    <%= image_tag "mic-pict.png", class:"none-report-picture" %>
   </div>
  <% end %>
 </ul>
</div>

<%= link_to(new_report_path, class: "report-btn") do %>
 <%= image_tag 'report-icon', class: "report-btn-icon"%>
 <span class="report-btn-text">投稿する</span>
<% end %>

<%= render "shared/footer" %>

app/views/reports/new.html.erb
<%= render "shared/second-header" %>

<div class="report-contents" >
  <div class="report-form-main" >
   <h1 class="report-form-subtitle">ライブレポートの記入</h1>
   <%= form_with model: @report, url: reports_path, class: "report-form", local: true do |f| %>

   <%= render 'shared/error-messages', model: f.object %>

    <div class="report-form-feild">
      <div class="report-form-wrap">
        <label class="form-text">タイトル</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="report-short-box">
        <%= f.text_field :title, class:"report-title", autofocus: true, placeholder: "レポートのタイトル(40文字まで)", maxlength:"40" %>
      </div>
    </div>
    <div class="report-form-feild">
      <div class="report-form-wrap">
        <label class="form-text">アーティスト</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="report-short-box">
        <%= f.text_field :artist, class:"report-artist", placeholder: "アーティスト名(正式名称で30文字)", maxlength:"30" %>
      </div>
    </div>
    <div class="report-form-field">
      <div class="report-form-wrap">
        <label class="form-text">本文</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="report-form-text-box">
       <%= f.text_area :text, class:"report-text", placeholder:"レポート内容(1200文字まで)", maxlength:"1200" %>
      </div>
    </div>
    <div class="report-form-field">
      <div class="report-form-wrap">
        <label class="form-text">このライブのオススメポイント</label>
        <span class="indispensable" style="color: black;">任意</span>
      </div>
      <div class="report-form-evaluate-box">
       <%= f.text_area :recommend, class:"report-item", placeholder:"オススメポイント(100文字まで)", maxlength:"100" %>
      </div>
    </div>
    <div class="report-rate-form">
      <div class="report-form-wrap">
        <label class="form-text">このライブの激しさ</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="rate-form-field" id="star1">
        <%= f.label :violent, "評価", class: "violent" %>
      </div>
      <div class="report-form-field">
        <div class="report-form-wrap">
          <label class="form-text">理由</label>
          <span class="indispensable" style="color: black;">任意</span>
        </div>
      </div>
      <div class="report-form-evaluate-box">
        <%= f.text_area :violent_reason, class:"report-item", placeholder:"理由(100文字まで)", maxlength:"100" %>
      </div>
    </div>
    <div class="report-rate-form">
      <div class="report-form-wrap">
        <label class="form-text">女性、家族連れの方へのオススメ度</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="rate-form-field" id="star2">
        <%= f.label :with_family, "評価", class: "with-family" %>
      </div>
      <div class="report-form-field">
        <div class="report-form-wrap">
          <label class="form-text">理由</label>
          <span class="indispensable" style="color: black;">任意</span>
        </div>
      </div>
      <div class="report-form-evaluate-box">
        <%= f.text_area :with_family_reason, class:"report-item", placeholder:"理由(100文字まで)", maxlength:"100" %>
      </div>
    </div>
    <div class="report-rate-form">
      <div class="report-form-wrap">
        <label class="form-text">ライブの予習必要度</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="rate-form-field" id="star3">
        <%= f.label :preparation, "評価", class: "preparation" %>
      </div>
      <div class="report-form-field">
        <div class="report-form-wrap">
          <label class="form-text">理由</label>
          <span class="indispensable" style="color: black;">任意</span>
        </div>
      </div>
      <div class="report-form-evaluate-box">
        <%= f.text_area :preparation_reason, class:"report-item", placeholder:"理由(100文字まで)", maxlength:"100" %>
      </div>
    </div>

      <%= render 'shared/rate-new' %>

    <div class="report-form-submit">
      <%= f.submit "投稿する", class:"report-send-btn" %>
    </div>
   <% end %>
  </div> 
</div>

<%= render "shared/footer" %>

app/views/reports/search.html.erb
<%= render "shared/second-header" %>

<div class="search-overall">
 <div class="search-wrap">
  <h2 class="search-subtitle">
   検索するキーワードを入力して下さい
  </h2>
 </div>
 <%= form_with( scope: :search, url: search_reports_path, method: :get, local: true, class:"search-form") do |f| %>
 <div class="search-form-field">
  <h3 class="search-form-subtitle">
   ・タイトル
  </h3>
 </div>
 <div class="search-form-contents">
  <%= f.text_field :title, value: @search_params[:title], autofocus: true, maxlength:"40", class:"search-form-input" %>
 </div>
 <div class="search-form-field">
  <h3 class="search-form-subtitle">
   ・アーティスト
  </h3>
 </div>
 <div class="search-form-contents">
  <%= f.text_field :artist, value: @search_params[:artist], maxlength:"30", class:"search-form-input" %>
 </div>
 <div class="search-form-field">
  <h3 class="search-form-subtitle">
   ・本文
  </h3>
 </div>
 <div class="search-form-text">
  <%= f.text_area :text, value: @search_params[:text], class:"search-form-input", maxlength:"100" %>
 </div>
 <div class="search-form-field">
  <h3 class="search-form-subtitle">
   ・ライブのオススメポイント
  </h3>
 </div>
 <div class="search-form-text">
  <%= f.text_area :recommend, value: @search_params[:recommend], class:"search-form-input", maxlength:"50" %>
 </div>

 <div class="search-form-btn-field">
  <%= submit_tag '検索する', class:"search-form-btn" %>
 </div>

 <% end %>

 <div class="search-report-wrap">
  <% unless @search_params.blank? %>
    <ul class="search-report-overall">
     <% @reports.each do |report| %>
     <li class="search-report-list">
      <%= link_to report_path(report.id) do %>
      <div class="search-report-field">
       <h3 class="search-report-nickname">
        <%= report.user.nickname %>
       </h3>
      </div>
      <div class="search-report-field">
       <h3 class="search-report-title">
        <%= report.title %>
       </h3>
      </div>
      <% end %>
     </li>
     <% end %>
    </ul>
  <% else %>
   <div class="search-report-none">
    <h3 class="search-result">
     該当するレポートはありません
    </h3>
   </div>
  <% end %>
 </div>
</div>

<%= render "shared/footer" %>

app/views/reports/show.html.erb
<%= render "shared/second-header" %>

<%= render "shared/flash" %>

<div class="report-show">
  <div class="report-box">
    <h3 class="ribbon8">タイトル</h3>
    <span class="show-title">
     <%= @report.title %>
    </span>
    <div class="show-content-box">
    <h3 class="ribbon8">アーティスト</h3>
    <span class="show-artist">
      <%= link_to @report.artist, artist_report_path(@report.id) %>
    </span>
   <div class="show-text-box">
    <h3 class="ribbon8">テキスト</h3>
    <span class="show-text">
      <%= safe_join(@report.text.split("\n"),tag(:br)) %>
    </span>
   </div>
   <div class="show-content-box">
    <h3 class="ribbon8">オススメポイント</h3>
    <span class="show-recommend">
      <%= @report.recommend %>
    </span>
   </div>
   <div class="show-content-box">
    <h3 class="ribbon8">ライブの評価</h3>
   </div>
   <div class="show-rate-box">
    <span class="rate-contents-top">ライブの激しさ</span>
    <div class="show-rate" id="star-violent-<%= @report.id %>"></div>
   </div>
   <div class="reason-box">
     <%= @report.violent_reason %>
   </div>
   <div class="show-rate-box">
    <span class="rate-contents">女性・家族連れの方へのオススメ度</span>
    <div class="show-rate" id="star-with_family-<%= @report.id %>"></div>
   </div>
   <div class="reason-box">
     <%= @report.with_family_reason %>
   </div>   
   <div class="show-rate-box">
    <span class="rate-contents">ライブの予習必要度</span>
    <div class="show-rate" id="star-preparation-<%= @report.id %>"></div>
   </div>
   <div class="reason-box">
     <%= @report.preparation_reason %>
   </div>

   <%= render "shared/rate-show" %>

   <div class="show-user-box">
    <h3 class="ribbon8">投稿者</h3>
    <span class="show-nickname">
      <%= link_to @report.user.nickname, user_path(@report.user.id) %>
    </span>
   </div>

   <div class="likes-box">
    <h3 class="ribbon8">イイネ☆</h3>
   </div>
   <div class="report-likes">
     
    <%= render 'likes/report', report: @report %>
    
   </div>
   

   <h3 class="ribbon8">コメント</h3>
   <ul id="report-comment-box">
    
    <%= render partial: "comments/index", locals: { comments: @comments} %>

    <div id="comment-error">
      <%= render 'shared/error-messages', model: @comment %>
    </div>
    
   </ul>
   <% if user_signed_in? %>
     <%= form_with model: [@report, @comment], class: "comment-form" do |f| %>

      <%= f.text_area :text, placeholder:"コメントの記入(400字まで)", maxlength:"400", class:"comment-input" %>
      <p class="comment-warn">
       ※ 相手に配慮した丁寧なコメントをしましょう
      </p>
      <%= f.submit "コメントを送信する", class:"comment-send-btn" %>
     <% end %>
   <% else %>
     <p class="comment-no-login">
      ※ いいねやコメントをするにはユーザー登録とログインが必要です ※
     </p>
   <% end %>

   <% if user_signed_in? && @report.user.id == current_user.id %>
      <%= link_to "レポートの編集", edit_report_path(@report.id), class: "edit-btn" %>
      <%= link_to "レポートの削除", report_path(@report.id), method: :delete, data: {confirm: "削除しますか？"}, class: "delete-btn" %>
   <% end %>
   
  </div>
</div>


<%= render "shared/footer" %>